### ISSUE TITLE
unsubscribe issues python 3?

### ISSUE THREAD

**Issue by jneilliii** [OctoPrint/OctoPrint-MQTT#101]
#### What were you doing?

Discussion on the issue in forum [here](https://community.octoprint.org/t/new-plugin-mqtt-for-psucontrol/33886?u=jneilliii)

Seems that unsubscribe may have an issue in Python 3

Quoting @cp2004...
> In Python 3, filter() returns an iterable object whereas in Python 2 it returned a list. Likely where the error comes from.

#### What did you expect to happen?

no errors when unsubscribing

#### What happened instead?

errors were thrown

#### Version of OctoPrint

unsure, assuming 1.6.0.

#### Version of the MQTT plugin

0.8.9

#### Link to octoprint.log

will work on reproducing issue and provide logs

#### Link to contents of Javascript console in the browser

n/a

#### Screenshot(s)/video(s) showing the problem

n/a

**Comment by oerkel47** [comment]
This did indeed fix it for my plugin. Do you still have a need for logs?

**Comment by jneilliii** [comment]
no, I don't think so @oerkel47 thanks for testing/confirming.
