### ISSUE TITLE
cant find topic for filament scale 

### ISSUE THREAD

**Issue by montyfert** [OctoPrint/OctoPrint-MQTT#141]
#### What were you doing?

hi @jneilliii  im trying to find filament scale mqtt topic any help would be great thanks.
martin

Ideally provide exact steps to follow in order to reproduce your problem: -->

1. ...
2. ...
3. ...

#### Version of the MQTT plugin 
0.8.13

**Comment by jneilliii** [comment]
OctoPrint has no such data available to it, so if you are using a plugin for that information you need to request mqtt integration there.

**Comment by montyfert** [comment]
thanks
