### ISSUE TITLE
Your plugin is causing errors in Home Assistant, regarding device/ entity naming schema.

### ISSUE THREAD

**Issue by nerlins** [OctoPrint/OctoPrint-MQTT#142]
See this post over in HA:

https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099

Your plugin is causing this error message in Home Assistant:

> Discovered entities with a name that starts with the device name
> 
> This stops working in version 2024.2.0. Please address before upgrading.
> 
> Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

sensor.octocr10_print_time
sensor.octosv01_tool_0_temperature
sensor.octocr10_soc_temperature
binary_sensor.octosv01_printing
button.octosv01_emergency_stop
switch.octocr10_emergency_stop
sensor.octosv01_print_file
sensor.camserver_memory_usage
binary_sensor.camserver_power_status
sensor.octosv01_bed_target
sensor.octosv01_print_time
sensor.octosv01_print_time_left
button.octosv01_shutdown_system
sensor.camserver_memory_available
sensor.octosv01_bed_temperature
sensor.octocr10_current_z
sensor.octocr10_print_progress
sensor.camserver_memory_used
button.octocr10_emergency_stop
sensor.camserver_memory_total
binary_sensor.octocr10_connected
switch.octocr10_shutdown_system
binary_sensor.octosv01_connected
button.octocr10_shutdown_system
sensor.octosv01_slicing_progress
sensor.octocr10_print_status
sensor.octocr10_print_estimated_time
button.octosv01_cancel_print
sensor.octocr10_tool_0_target
sensor.octocr10_bed_target
button.octocr10_restart_server
sensor.octosv01_current_z
sensor.octocr10_slicing_progress
sensor.octocr10_bed_temperature
sensor.octosv01_last_event
switch.octosv01_pause_print
button.octocr10_cancel_print
button.octosv01_reboot_system
binary_sensor.octocr10_printing
switch.octosv01_emergency_stop
switch.octosv01_shutdown_system
switch.octosv01_cancel_print
sensor.octocr10_print_time_left
sensor.octosv01_soc_temperature
switch.octocr10_connect_to_printer
switch.octocr10_pause_print
sensor.octosv01_approximate_completion_time
sensor.camserver_cpu_usage
sensor.octocr10_print_file
sensor.octosv01_tool_0_target
sensor.octocr10_last_event
sensor.octocr10_tool_0_temperature
switch.octosv01_connect_to_printer
button.octosv01_restart_server
sensor.octosv01_print_estimated_time
button.octocr10_reboot_system
sensor.octocr10_approximate_completion_time
sensor.octosv01_slicing_file
sensor.octocr10_slicing_file
switch.octocr10_cancel_print
sensor.octosv01_print_status
sensor.octosv01_print_progress

**Comment by jneilliii** [comment]
This plugin is not the home assistant plugin. That one can be found at https://github.com/cmroche/OctoPrint-HomeAssistant.

**Comment by nerlins** [comment]
Sounds good. Redirecting all issues to the HA plugin.

**Comment by nerlins** [comment]
Sounds good. Redirecting all issues to the HA plugin.
