### ISSUE TITLE
Feature request: Time remaining

### ISSUE THREAD

**Issue by liftoff** [OctoPrint/OctoPrint-MQTT#16]
Doesn't appear that the plugin sends out the time remaining on any channels.  Is there any way we can get that info published?

**Comment by sprior** [comment]
I'd love to see time remaining/time elapsed added as well.  MQTT is great, I've already added an Octoprint Progress gauge to a node-red dashboard.

**Comment by kanflo** [comment]
That is something I would like too. It does however require a change to OctoPrint rather than this plugin as OctoPrint currently does not send the time remaining to the plugins.

**Comment by kezmdor** [comment]
I am also very interested in something like ETA or ETL.

**Comment by dp106** [comment]
You could query the api to get information on the current job and time remaining:  
[http://docs.octoprint.org/en/master/api/job.html#id3](url)
(You might need to scroll down a bit to find the section "Retrieve information about the current job")

**Comment by jneilliii** [comment]
It looks like this may have been accounted for in the devel branch, but has yet to be release to the official version.  I'm going to test the devel branch over the weekend and if everything looks stable will push to master and release official version 0.8.0 next week.  @tedder & @Kunsi, is that good for you guys?

**Comment by tedder** [comment]
Oh, nice. I was going to explore what data was in the Octoprint hook to see if we could support it. That's better yet.

**Comment by jneilliii** [comment]
I just made a small change to dev to only include the extended printer_data attribute to the printing progress topic rather than with every topic.  That seems to make more sense to me, but let me know what you guys think.

**Comment by jneilliii** [comment]
This feature has been released as version 0.8.0.  Ready for your fixes @tedder on the other issues.
