### ISSUE TITLE
version compatible?

### ISSUE THREAD

**Issue by brunkj** [OctoPrint/OctoPrint-MQTT#2]
does this work with 1.2.7 and 1.2.8?

**Comment by foosel** [comment]
Sorry, the notification for this must have gotten buried in all the other OctoPrint related github messages, I only just now saw it :(

I guess you are talking about OctoPrint? It definitely should.

**Comment by brunkj** [comment]
hmmm haven't been able to get it to work.

**Comment by foosel** [comment]
Some more details would be nice ;) Were there problems installing it? Configuring it? Running it? What happens? What did you expect to happen? What didn't, what did, what did you try? What's in `octoprint.log`?

I don't sit in front of your setup, I can't see the issue myself, so I can't help you unless you tell me about it.

**Comment by Locbit** [comment]
I have a question can I use this plugin to post basic JSON.

**Comment by foosel** [comment]
@Locbit sorry, I don't understand the question, please provide more details (in a different ticket). It's a plugin for getting OctoPrint to talk to MQTT brokers.

@brunkj anything more to provide here? If not, I'll close it.
