### ISSUE TITLE
Progress shown in Domoticz via node-red flow

### ISSUE THREAD

**Issue by bjacobse** [OctoPrint/OctoPrint-MQTT#23]
Hi, not sure how to provide info, as this is not an issue:
I am using Domoticz as homeautomation server, and have created this node-red flow that uses this nice MQTT octoprint plugin

https://www.domoticz.com/forum/viewtopic.php?f=21&t=14021&p=162935#p162935

**Comment by foosel** [comment]
@bjacobse nice! I've enabled the Wiki on this repo and added this there :)
