### ISSUE TITLE
Feedback when printing from SDCARD

### ISSUE THREAD

**Issue by Allycat1972** [OctoPrint/OctoPrint-MQTT#24]
Hi. Printing using the Octoprint server is sometimes very slow when printing complex shapes so I often print from the SDCARD. Currrently there is no status / update when using this method.  Is there any way to get regular status / feedback from the 3D Printer via MQTT?  I publish the MQTT topics using OpenHAB so I can monitor the progress remotely. Many thanks, Andrew.

**Comment by foosel** [comment]
I cannot reproduce this here, progress reports while printing from SD arrive just flawlessly.

Of course, the SD print must be started *through OctoPrint*, otherwise OctoPrint won't even know you are printing from SD and also can't check progress with your printer.

**Comment by foosel** [comment]
@Allycat1972 Can this be closed?

**Comment by Allycat1972** [comment]
@foosel Yes, thank-you for the response.
