### ISSUE TITLE
Add SSL support (encryption and server identity, optionally also client certificates)

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint-MQTT#3]
The MQTT plugin currently does not support connecting to SSL secured brokers. It should be adjusted to change that.

TODOs:

  * [ ] allow to specify that the connection is to be made via SSL
  * [ ] allow uploading/specifying path to a cacert file to use for checking the broker certificate (mandatory for connecting to broker via SSL, maybe there's some meaningful default path to use here?)
  * [ ] Optional: allow to specify a client certificate and key file path to use to authenticate with the broker 
  * [ ] use the provided configuration to change client's connection parameters via `tls_set`

**Comment by jawilson** [comment]
I'll pick this up over the next week or so.
