### ISSUE TITLE
Query informations

### ISSUE THREAD

**Issue by Psychokiller1888** [OctoPrint/OctoPrint-MQTT#45]
#### What were you doing?

Developping my home assistant

#### Version of OctoPrint

1.3.9

#### Version of the MQTT plugin

0.7.1

#### Screenshot(s)/video(s) showing the problem

How do we query data? It's good to have randomly heartbeat, but querying the progress and others would make sense?

**Comment by foosel** [comment]
Read the README again, it contains information on which topics "progress and others" are published. MQTT is a publish/subscribe protocol, there's no querying of data, there's only subscribing to topics and waiting for events to be published on them.

**Comment by Psychokiller1888** [comment]
No....

First of all, the readme doesn't give al lthe topics, found them though

MQTT can be bidirectional, meaning your plugin could listen for messages sent to it from another devices and send out another message...

**Comment by foosel** [comment]
The plugin doesn't subscribe to any topics, it only publishes (otherwise that would be documented). There already is an existing feature request for changing that, waiting for someone to implement it.

If there are any topics missing from the documentation please send a PR to fix this.

**Comment by Psychokiller1888** [comment]
Waiting for someone to implement it... Ok.... Well, I'll do it myself then, np

**Comment by foosel** [comment]
> Well, I'll do it myself then, np 

That's the spirit! 👍
