### ISSUE TITLE
Up for adoption

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint-MQTT#47]
I have my hands way too full with OctoPrint's maintenance to give this plugin the attention it needs. Hence I'm looking for a new maintainer to adopt it.

**Comment by tedder** [comment]
I would like to take this, or share the ownership if anyone else is interested.

**Comment by foosel** [comment]
@Kunsi already raised her hand, but I'm not sure, maybe she'd also be interested in shared ownership. I'll leave that for y'all to figure out ;) 

In any case, thanks for the interest! :)

**Comment by Kunsi** [comment]
Any help is welcome, so feel free to join the team :)

**Comment by foosel** [comment]
@Kunsi you should have admin permissions, so you should be able to invite @tedder as a collaborator

**Comment by Kunsi** [comment]
Oh, yeah. Done that now :3

**Comment by tedder** [comment]
thanks!

**Comment by jneilliii** [comment]
I'd like to be part of this team too if that's cool with you guys.

**Comment by tedder** [comment]
jneilliii is pretty much the octoprint plugin god.

**Comment by jneilliii** [comment]
You're funny Ted, I just hack things together.

**Comment by jneilliii** [comment]
Thanks for the invite, let me know how I can help.  I'll probably start by going through and flushing out some of the issues. Adoption complete, readme updated removing adoption notice.
