### ISSUE TITLE
configurable _timestamp field name?

### ISSUE THREAD

**Issue by tedder** [OctoPrint/OctoPrint-MQTT#48]
I'm pushing output of this plugin into Elasticsearch, which doesn't like having a field use its internal name of _timestamp.

Perhaps the name of that field could be configurable? I might do it but I have a bunch of loose ends, so I wanted to at least place it here.

**Comment by tedder** [comment]
wondering if @foosel has seen this since they use ELK.

**Comment by RedWagon** [comment]
+1 to this, I'm having issues using the timestamp in AWS IoT due to the SQL selection language used to interpret MQTT payloads when executing rules.

**Comment by jneilliii** [comment]
Incorporated into branch 1.8.2 for testing.  Install using the following url in plugin manager to verify.

https://github.com/OctoPrint/OctoPrint-MQTT/archive/0.8.2.zip
