### ISSUE TITLE
Feature request: publish Printer Profile

### ISSUE THREAD

**Issue by khoinguyen** [OctoPrint/OctoPrint-MQTT#54]
Can the plugin publish the Printer Profile? At least the Printer Id
http://docs.octoprint.org/en/master/modules/printer.html#module-octoprint.printer.profile

I'm using the plugin to create a dashboard to monitor multiple printers, without the Printer Id, it's impossible to know which data is from which printer

**Comment by tedder** [comment]
I just change the mqtt prefix, fwiw.

**Comment by foosel** [comment]
That would also be my recommmendation

**Comment by khoinguyen** [comment]
@tedder @foosel thank you. That's a good suggestion
