### ISSUE TITLE
Feature request: Configure retain flag (for AWS IoT)

### ISSUE THREAD

**Issue by RedWagon** [OctoPrint/OctoPrint-MQTT#55]
#### What were you doing?

Publishing to AWS IoT via mosquitto broker 
https://aws.amazon.com/blogs/iot/how-to-bridge-mosquitto-mqtt-broker-to-aws-iot/

#### What did you expect to happen?

AWS IoT would receive the messages

#### What happened instead?

All messages from the mosquitto broker stopped being processed by AWS, even ones unrelated to OctoPrint.

#### Version of OctoPrint

1.3.10

#### Version of the MQTT plugin

0.8.0

#### Used MQTT broker and its version

mosquitto 1.5.5

#### Workaround:
Clone plugin source 
```
cd OctoPrint-MQTT/octoprint_mqtt/
sed -i 's/retained=True/retained=False/' __init__.py
sed -i 's/retain=True/retain=False/' __init__.py
```
Install plugin

**Comment by jneilliii** [comment]
@RedWagon, would making this an optional setting work for you?  I'd be concerned with some of the messages being retained due to the discussion over in #46.

**Comment by tedder** [comment]
[AWS docs support the need to not retain *anything*](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt.html):
> The MQTT specification provides a provision for the publisher to request that the broker retain the last message sent to a topic and send it to all future topic subscribers. AWS IoT does not support retained messages. If a request is made to retain messages, the connection is disconnected.

It'll definitely need to be a setting.
