### ISSUE TITLE
Unable to Push Commands

### ISSUE THREAD

**Issue by buzurk26** [OctoPrint/OctoPrint-MQTT#80]
#### What were you doing?

Trying to push simple commands back to OctoPrint via MQTT, I only want the connect command ultimately but may expand this later.

**Screenshots** -https://imgur.com/a/x87twye

- Running latest plugin and notice that there is no index column anymore?
- Using MQTTExplorer for windows also in an attempt to issue commands.

It also seems like the MQTT-Subscribe is not showing my topics anymore, it did before, but now it just shows a debug one https://imgur.com/WibChuK

#### What did you expect to happen?
Tell Octpoprint to connect to printer

#### What happened instead?
Nothing

#### Version of OctoPrint
OctoPrint 1.3.12 running on OctoPi 0.17.0

#### Version of the MQTT plugin
MQTT (0.8.6)
MQTT Subscribe (0.1.1)

#### Used MQTT broker and its version
Home Assistant Mosquitto Broker 5.1
https://github.com/home-assistant/hassio-addons/tree/master/mosquitto

#### Link to octoprint.log
https://gist.github.com/buzurk26/c046a51b1f77bc19672f87b9984e053f

**Comment by jneilliii** [comment]
This is an issue with the subscribe plugin, not this one. Since you can't publish commands in the base MQTT plugin. There is significant development work going in with the subscribe plugin already, expect additional changes necessary in your end in the next release.
