### ISSUE TITLE
No messages recieved

### ISSUE THREAD

**Issue by MalakanC** [OctoPrint/OctoPrint-MQTT#93]
#### What were you doing?

First time use, testing the functionality and connectivity. 

From the log I see:
octoprint.plugins.mqtt - INFO - Connected to mqtt broker
octoprint.plugin - DEBUG - Calling on_event on mqtt

I have the `topic` set to `octoPrint/`. I do not see any messages from octoPrint when subbing to `octoPrint` or `octoPrint/`

#### What did you expect to happen?

Expected to see the payload

#### What happened instead?

Nothing

#### Version of OctoPrint

OctoPrint 1.5.2 Python 2.7.16 OctoPi 0.17.0

#### Version of the MQTT plugin

0.8.7

#### Used MQTT broker and its version

mosquitto 1.6.9  (MQTT v3.1.1 broker)

#### Link to octoprint.log

https://pastebin.com/Jn7QJ60K

#### Link to contents of Javascript console in the browser

mosquitto_sub -t 'octoPrint/' -u USER-P PASS

**Comment by hopsor** [comment]
Hi @MalakanC, did you manage to fix this? I'm having the same issues but I don't have any clue. Apparently the connection to the broker is ok and Octoprint is sending the messages from what I see in the logs. But I don't see them being published in the broker :-(
