### ISSUE TITLE
Plugin no longer publishes after upgrading to 0.8.8

### ISSUE THREAD

**Issue by halfluck** [OctoPrint/OctoPrint-MQTT#99]
Hey Guys,

My octoprint just upgraded me to 0.8.8 and now Home Assistant can no longer see my instances.
Is there anything that has changed or I need to change to rectify this?

Speak soon Rob.

**Comment by Kunsi** [comment]
Yes, indeed there's a bug I didn't catch when reviewing #98. I will publish a fix soon (some time over the day).

**Comment by halfluck** [comment]
Phew! thankyou so much for the quick reply, I was going spare trying to work it out :)

**Comment by Kunsi** [comment]
Should be fixed now. Tested with python2.7.18 and 3.9.2, both were able to publish successfully.

**Comment by halfluck** [comment]
Thanks so much, can confirm working Ok with Py3 now
